language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python3 setup.py install
  - pip install codecov
# command to run tests
script:
  - coverage run --branch --omit={envdir}/*,tests/*.py -m unittest discover tests "*_tests.py"

after_success:
  - codecov
